### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by sergeyklay** [steffengy/pico-php-parser#2]
Hello, 

Cold you please provide minimal info about installing, testing, etc.

**Comment by steffengy** [comment]
Planning to do that soon, documentation will get more in some time.
Currently I'm aiming to get it to a stage where it can parse most "industry" level code (laravel currently).
Then I also need to setup CI, readme and other documentation aswell as more parser functionality.

I'll try to get started on the readme soon though :)

**Comment by steffengy** [comment]
@sergeyklay 
initial (very rudimentary) documentation is up aswell as first CI support, as
described in the readme. laravel also parses finally :8ball:
